export const SET_USERS='SET_USERS';
export const UPDATE_USERS='UPDATE_USERS';
export const LOADING_USERS='LOADING_USERS';
export const CHANGE_MODE='CHANGE_MODE';
export const GET_VALIDATION_ERRORS='GET_VALIDATION_ERRORS';
export const CLEAR_VALIDATION_ERROR='CLEAR_VALIDATION_ERROR';